#===----------------------------- .travis.yml ------------------------------===#
#
#                         Obliging Ode & Unsung Anthem
#
# This source file is part of the Obliging Ode and Unsung Anthem open source
# projects.
#
# Copyright (C) 2019 Antti Kivi
# All rights reserved

language: cpp

sudo: false

matrix:
  include:

  #===----------------------------------------------------------------------===#
  #==- Linux - GCC ----------------------------------------------------------==#
  #===----------------------------------------------------------------------===#

  # Linux: Ubuntu Trusty 14.04 C++17 GCC 7
  # - os: linux
  #   dist: trusty
  #   compiler: gcc
  #   env:
  #   - COMPILER_NAME=gcc
  #   - CXX=g++-7
  #   - CC=gcc-7
  #   - BUILD_PRESET=travis_linux_gcc7_cxx17
  #   - ENABLE_COVERAGE=false
  #   addons:
  #     apt:
  #       packages:
  #       - g++-7
  #       - xorg-dev
  #       - libglu1-mesa-dev
  #       - build-essential
  #       sources: &sources
  #       - ubuntu-toolchain-r-test

  # Linux: Ubuntu Trusty 14.04 C++17 GCC 7 with Make
  - os: linux
    dist: trusty
    compiler: gcc
    env:
    - COMPILER_NAME=gcc
    - CXX=g++-7
    - CC=gcc-7
    - BUILD_PRESET=travis_linux_gcc7_cxx17_make
    - ENABLE_COVERAGE=false
    addons:
      apt:
        packages:
        - g++-7
        - xorg-dev
        - libglu1-mesa-dev
        - build-essential
        sources: &sources
        - ubuntu-toolchain-r-test

  # Linux: Ubuntu Trusty 14.04 C++17 GCC 7 + Coverage
  - os: linux
    dist: trusty
    compiler: gcc
    env:
    - COMPILER_NAME=gcc
    - CXX=g++-7
    - CC=gcc-7
    - BUILD_PRESET=travis_linux_gcc7_cxx17_coverage
    - ENABLE_COVERAGE=true
    addons:
      apt:
        packages:
        - g++-7
        - xorg-dev
        - libglu1-mesa-dev
        - build-essential
        - lcov
        sources: *sources

  #===----------------------------------------------------------------------===#
  #==- Linux - Clang --------------------------------------------------------==#
  #===----------------------------------------------------------------------===#

  # Linux: Ubuntu Trusty 14.04 C++17 Clang 6.0
  - os: linux
    dist: trusty
    compiler: clang
    env:
    - COMPILER_NAME=clang
    - CXX=clang++
    - CC=clang
    - BUILD_PRESET=travis_linux_clang60_cxx17
    - ENABLE_COVERAGE=false
    addons:
      apt:
        packages:
        - xorg-dev
        - libglu1-mesa-dev
        - build-essential
        sources: *sources

  #===----------------------------------------------------------------------===#
  #==- Darwin - Apple Clang -------------------------------------------------==#
  #===----------------------------------------------------------------------===#

  # Darwin: macOS 10.10 Xcode 6.4 C++17 Clang
  # - os: osx
  #   osx_image: xcode6.4
  #   compiler: clang
  #   env:
  #   - COMPILER_NAME=clang
  #   - CXX=clang++
  #   - CC=clang
  #   - BUILD_PRESET=travis_darwin_xcode64_clang_cxx17
  #   - ENABLE_COVERAGE=false
  #   - ODE_PYTHON=python3
  #   - ODE_PIP=pip3

  # Darwin: macOS 10.11 Xcode 7.3.1 C++17 Clang
  - os: osx
    osx_image: xcode7.3
    compiler: clang
    env:
    - COMPILER_NAME=clang
    - CXX=clang++
    - CC=clang
    - BUILD_PRESET=travis_darwin_xcode73_clang_cxx17
    - ENABLE_COVERAGE=false

  # Darwin: macOS 10.12 Xcode 8.3.3 C++17 Clang
  - os: osx
    osx_image: xcode8.3
    compiler: clang
    env:
    - COMPILER_NAME=clang
    - CXX=clang++
    - CC=clang
    - BUILD_PRESET=travis_darwin_xcode83_clang_cxx17
    - ENABLE_COVERAGE=false
    - ODE_PYTHON=python2
    - ODE_PIP=pip2

  # Darwin: macOS 10.13 Xcode 9.3 beta C++17 Clang
  - os: osx
    osx_image: xcode9.3beta
    compiler: clang
    env:
    - COMPILER_NAME=clang
    - CXX=clang++
    - CC=clang
    - BUILD_PRESET=travis_darwin_xcode93_clang_cxx17
    - ENABLE_COVERAGE=false

before_install:
- cd $TRAVIS_BUILD_DIR/..
- chmod +x unsung-anthem/utils/travis/before_install.sh
- ./unsung-anthem/utils/travis/before_install.sh

install:
- cd $TRAVIS_BUILD_DIR/..
- chmod +x unsung-anthem/utils/travis/install.sh
- ./unsung-anthem/utils/travis/install.sh

script:
- cd $TRAVIS_BUILD_DIR/..
- chmod +x unsung-anthem/utils/travis/script.sh
- ./unsung-anthem/utils/travis/script.sh

after_script:
- cd $TRAVIS_BUILD_DIR
- chmod +x utils/travis/after_script.sh
- ./utils/travis/after_script.sh
