language: cpp

sudo: false

cache:
  apt: true
  pip: true

matrix:
  include:
  # Linux Precise C++11 GCC 4.8.4
   - os: linux
     compiler: gcc
     env: ANTHEM_BUILD_PRESET=travis_linux_gcc48_cpp11

   # Linux Precise C++14 GCC 5
   - os: linux
     compiler: gcc
     env: ANTHEM_BUILD_PRESET=travis_linux_gcc5_cpp14
     addons:
      apt:
        packages:
         - g++-5
        sources: &sources
         - ubuntu-toolchain-r-test
         - llvm-toolchain-precise
         - llvm-toolchain-precise-3.7
         - llvm-toolchain-precise-3.6

   # Linux Precise C++17 GCC 7
   - os: linux
     compiler: gcc
     env: ANTHEM_BUILD_PRESET=travis_linux_gcc7_cpp17
     addons:
      apt:
        packages:
         - g++-7
        sources: *sources

   # Linux Precise C++11 Clang 3.3
   - os: linux
     compiler: clang
     env: ANTHEM_BUILD_PRESET=travis_linux_clang33_cpp11
     addons:
      apt:
        packages:
         - clang-3.3
        sources: *sources

   # Linux Precise C++14 Clang 3.5
   - os: linux
     compiler: clang
     env: ANTHEM_BUILD_PRESET=travis_linux_clang35_cpp14

   # Linux Precise C++17 Clang 4
   - os: linux
     compiler: clang
     env: ANTHEM_BUILD_PRESET=travis_linux_clang4_cpp17
     addons:
      apt:
        packages:
         - clang-4
        sources: *sources



install:
 - pip install requests

script:
 - cd $TRAVIS_BUILD_DIR/..
 - unsung-anthem/utils/build-script --preset ${ANTHEM_BUILD_PRESET}
