language: cpp

sudo: false

cache: apt

matrix:
  include:
  # Linux: Ubuntu Precise 12.04 C++11 GCC 4.8
   - os: linux
     dist: precise
     compiler: gcc
     env: COMPILER_NAME=gcc CXX=g++-4.8 CC=gcc-4.8 ANTHEM_BUILD_PRESET=travis_linux_gcc48_cpp11
     addons:
      apt:
        packages:
         - g++-4.8
         - xorg-dev
         - libglu1-mesa-dev
         - build-essential
        sources: &sources
         - ubuntu-toolchain-r-test
         - llvm-toolchain-trusty
         - llvm-toolchain-trusty-4.0
         - llvm-toolchain-trusty-3.9
         - llvm-toolchain-precise
         - llvm-toolchain-precise-3.9
         - llvm-toolchain-precise-3.8
         - llvm-toolchain-precise-3.7
         - llvm-toolchain-precise-3.6
         - llvm-toolchain-precise-3.5

   # Linux: Ubuntu Precise 12.04 C++14 GCC 5
   - os: linux
     dist: precise
     compiler: gcc
     env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5 ANTHEM_BUILD_PRESET=travis_linux_gcc5_cpp14
     addons:
      apt:
        packages:
         - g++-5
         - xorg-dev
         - libglu1-mesa-dev
         - build-essential
        sources: *sources

   # Linux: Ubuntu Precise 12.04 C++14 GCC 6
   - os: linux
     dist: precise
     compiler: gcc
     env: COMPILER_NAME=gcc CXX=g++-6 CC=gcc-6 ANTHEM_BUILD_PRESET=travis_linux_gcc6_cpp14
     addons:
      apt:
        packages:
         - g++-6
         - xorg-dev
         - libglu1-mesa-dev
         - build-essential
        sources: *sources

   # Linux: Ubuntu Trusty 14.04 C++17 GCC 7
   - os: linux
     dist: trusty
     compiler: gcc
     env: COMPILER_NAME=gcc CXX=g++-7 CC=gcc-7 ANTHEM_BUILD_PRESET=travis_linux_gcc7_cpp17
     addons:
      apt:
        packages:
         - g++-7
         - xorg-dev
         - libglu1-mesa-dev
         - build-essential
        sources: *sources

   # Linux: Ubuntu Trusty 14.04 C++11 Clang 3.5
   - os: linux
     dist: trusty
     compiler: clang
     env: COMPILER_NAME=clang CXX=clang++-3.5 CC=clang-3.5 ANTHEM_BUILD_PRESET=travis_linux_clang35_cpp11
     addons:
      apt:
        packages:
         - clang-3.5
         - xorg-dev
         - libglu1-mesa-dev
         - build-essential
         - libc++-dev
        sources: *sources

   # Linux: Ubuntu Trusty 14.04 C++14 Clang 3.5
   - os: linux
     dist: trusty
     compiler: clang
     env: COMPILER_NAME=clang CXX=clang++-3.5 CC=clang-3.5 ANTHEM_BUILD_PRESET=travis_linux_clang35_cpp14
     addons:
      apt:
        packages:
          - clang-3.5
          - xorg-dev
          - libglu1-mesa-dev
          - build-essential
          - libc++-dev
        sources: *sources

   # Linux: Ubuntu Trusty 14.04 C++14 Clang 3.6
   - os: linux
     dist: trusty
     compiler: clang
     env: COMPILER_NAME=clang CXX=clang++-3.6 CC=clang-3.6 ANTHEM_BUILD_PRESET=travis_linux_clang36_cpp14
     addons:
      apt:
        packages:
          - clang-3.6
          - xorg-dev
          - libglu1-mesa-dev
          - build-essential
          - libc++-dev
        sources: *sources

   # Linux: Ubuntu Trusty 14.04 C++14 Clang 3.7
   - os: linux
     dist: trusty
     compiler: clang
     env: COMPILER_NAME=clang CXX=clang++-3.7 CC=clang-3.7 ANTHEM_BUILD_PRESET=travis_linux_clang37_cpp14
     addons:
      apt:
        packages:
          - clang-3.7
          - xorg-dev
          - libglu1-mesa-dev
          - build-essential
          - libc++-dev
        sources: *sources

   # Linux: Ubuntu Trusty 14.04 C++14 Clang 3.8
   - os: linux
     dist: trusty
     compiler: clang
     env: COMPILER_NAME=clang CXX=clang++-3.8 CC=clang-3.8 ANTHEM_BUILD_PRESET=travis_linux_clang38_cpp14
     addons:
      apt:
        packages:
          - clang-3.8
          - xorg-dev
          - libglu1-mesa-dev
          - build-essential
          - libc++-dev
        sources: *sources

   # Linux: Ubuntu Trusty 14.04 C++14 Clang 3.9
   - os: linux
     dist: trusty
     compiler: clang
     env: COMPILER_NAME=clang CXX=clang++-3.9 CC=clang-3.9 ANTHEM_BUILD_PRESET=travis_linux_clang39_cpp14
     addons:
      apt:
        packages:
          - clang-3.9
          - xorg-dev
          - libglu1-mesa-dev
          - build-essential
          - libc++-dev
        sources: *sources

   # Linux: Ubuntu Trusty 14.04 C++17 Clang 4.0
   - os: linux
     dist: trusty
     compiler: clang
     env: COMPILER_NAME=clang CXX=clang++-4.0 CC=clang-4.0 ANTHEM_BUILD_PRESET=travis_linux_clang40_cpp17
     addons:
      apt:
        packages:
          - clang-4.0
          - xorg-dev
          - libglu1-mesa-dev
          - build-essential
          - libc++-dev
        sources: *sources

install:
 - ${CC} --version
 - ${CXX} --version
 - pip install --user requests

script:
 - cd $TRAVIS_BUILD_DIR/..
 - unsung-anthem/utils/build-script --preset ${ANTHEM_BUILD_PRESET}
