language: generic

sudo: false

matrix:
  include:
  # Linux: Ubuntu Precise 12.04 C++11 GCC 4.8
   - os: linux
     dist: precise
     env: COMPILER_NAME=gcc CXX=g++-4.8 CC=gcc-4.8 ANTHEM_BUILD_PRESET=travis_linux_gcc48_cpp11
     addons:
      apt:
        packages:
         - g++-4.8
         - xorg-dev
         - libglu1-mesa-dev
         - build-essential
        sources: &sources
         - ubuntu-toolchain-r-test
         - llvm-toolchain-trusty
         - llvm-toolchain-trusty-4.0
         - llvm-toolchain-trusty-3.9
         - llvm-toolchain-trusty-3.8
         - llvm-toolchain-trusty-3.7
         - llvm-toolchain-trusty-3.6
         - llvm-toolchain-precise
         - llvm-toolchain-precise-4.0
         - llvm-toolchain-precise-3.9
         - llvm-toolchain-precise-3.8
         - llvm-toolchain-precise-3.7
         - llvm-toolchain-precise-3.6

   # Linux: Ubuntu Precise 12.04 C++14 GCC 5
   - os: linux
     dist: precise
     env: COMPILER_NAME=gcc CXX=g++-4.8 CC=gcc-4.8 ANTHEM_BUILD_PRESET=travis_linux_gcc5_cpp14
     addons:
      apt:
        packages:
         - g++-5
         - xorg-dev
         - libglu1-mesa-dev
         - build-essential
        sources: *sources

   # Linux: Ubuntu Precise 12.04 C++11 Clang 3.5
   - os: linux
     dist: precise
     env: COMPILER_NAME=clang CXX=clang++-3.5 CC=clang-3.5 ANTHEM_BUILD_PRESET=travis_linux_clang35_cpp11
     addons:
      apt:
        packages:
         - clang++-3.5
         - xorg-dev
         - libglu1-mesa-dev
         - build-essential
        sources: *sources

   # Linux: Ubuntu Trusty 14.04 C++14 Clang 3.5
   - os: linux
     dist: trusty
     env: COMPILER_NAME=clang CXX=clang++-3.5 CC=clang-3.5 ANTHEM_BUILD_PRESET=travis_linux_clang35_cpp14
     addons:
      apt:
        packages:
          - clang-3.5
          - xorg-dev
          - libglu1-mesa-dev
          - build-essential
        sources: *sources

install:
 - if [ ${COMPILER_NAME} == "clang" ]; then clang --version; else gcc --version; fi
 - pip install --user requests

script:
 - cd $TRAVIS_BUILD_DIR/..
 - unsung-anthem/utils/build-script --preset ${ANTHEM_BUILD_PRESET}
