language: cpp

sudo: false

matrix:
  include:
  # Linux: Ubuntu Precise C++11 GCC 4.8.4
   - os: linux
     compiler: gcc
     env: ANTHEM_BUILD_PRESET=travis_linux_gcc48_cpp11
     addons:
      apt:
        packages: &packages
         - xorg-dev
         - libglu1-mesa-dev
        sources: &sources
         - ubuntu-toolchain-r-test
         - llvm-toolchain-precise
         - llvm-toolchain-precise-3.7
         - llvm-toolchain-precise-3.6

   # Linux: Ubuntu Precise C++14 GCC 5
   - os: linux
     compiler: gcc
     env: ANTHEM_BUILD_PRESET=travis_linux_gcc5_cpp14
     addons:
      apt:
        packages:
         - g++-5
         - xorg-dev
         - libglu1-mesa-dev
        sources: *sources

   # Linux: Ubuntu Precise C++11 Clang 3.4
   - os: linux
     compiler: clang
     env: ANTHEM_BUILD_PRESET=travis_linux_clang34_cpp11
     addons:
      apt:
        packages: *packages
        sources: *sources

   # Linux: Ubuntu Trusty C++14 Clang 3.5
   - os: linux
     compiler: clang
     dist: trusty
     env: ANTHEM_BUILD_PRESET=travis_linux_clang35_cpp14
     addons:
      apt:
        packages:
          - clang-3.5
          - xorg-dev
          - libglu1-mesa-dev
        sources: *sources

install:
 - pip install --user requests

script:
 - cd $TRAVIS_BUILD_DIR/..
 - unsung-anthem/utils/build-script --preset ${ANTHEM_BUILD_PRESET}
