version: '0.1.0-dev.{build}'

image:
 - Visual Studio 2015
 - Visual Studio 2017

platform:
 - x86
 - x64

configuration: Debug

environment:
  ANTHEM_OAUTH:
    secure: 9v/VvJm25wmGY1pEfu1jKPfjlY0S3/XD+/V4QcNAs9p0sNUSkmzuAvYK8IobENjd

before_build:
 - echo %PATH%
 - where /r c:\ msbuild*
 - pip install requests
 - cd %APPVEYOR_BUILD_FOLDER%\..
 - python unsung-anthem\utils\build-script --preset=appveyor_windows_vs15
