version: '0.1.0-dev.{build}'

image:
 - Visual Studio 2015
 - Visual Studio 2017

platform:
 - x86
 - x64

configuration: Debug

environment:
  ANTHEM_OAUTH:
    secure: 9v/VvJm25wmGY1pEfu1jKPfjlY0S3/XD+/V4QcNAs9p0sNUSkmzuAvYK8IobENjd

install:
 - IF /i "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2015" SET ANTHEM_CMAKE_GENERATOR=Visual_Studio_14_2015
 - IF /i "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" SET ANTHEM_CMAKE_GENERATOR=Visual_Studio_15_2017
 - IF /i "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2015" SET ANTHEM_PRESET=appveyor_windows_vs14
 - IF /i "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" SET ANTHEM_PRESET=appveyor_windows_vs15
 - pip install requests
 - cd %APPVEYOR_BUILD_FOLDER%\..
 - python unsung-anthem\utils\build-script --preset=%ANTHEM_PRESET% --install

build_script:
 - cd %APPVEYOR_BUILD_FOLDER%\..
 - python unsung-anthem\utils\build-script --preset=%ANTHEM_PRESET% --build

test_script:
 - cd %APPVEYOR_BUILD_FOLDER%\..
 - python unsung-anthem\utils\build-script --preset=%ANTHEM_PRESET% --run-test
