#===---------------------------- apppveyor.yml -----------------------------===#
#
#                         Obliging Ode & Unsung Anthem
#
# This source file is part of the Obliging Ode and Unsung Anthem open source
# projects.
#
# Copyright (c) 2019 Antti Kivi
# Licensed under GNU Affero General Public License v3.0

version: '0.1.0-dev.1+appveyor-{build}'

image:
 - Visual Studio 2017

platform:
 - x86
 - x64

configuration: Debug

clone_folder: C:\projects\unsung-anthem\unsung-anthem

environment:
  ANTHEM_OAUTH:
    secure: 4OCwwnyLZsHZxRdZm466OrFGcYaE+rcfNAoVZWhsvpA+pBzYoMeXbxzINJDwXBgv

install:
 - IF /i "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2015" SET ANTHEM_CMAKE_GENERATOR=Visual_Studio_14_2015
 - IF /i "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" SET ANTHEM_CMAKE_GENERATOR=Visual_Studio_15_2017
 - IF /i "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" SET ANTHEM_PRESET=appveyor_windows_vs15_cxx17
 - pip install requests

build_script:
 - cd %APPVEYOR_BUILD_FOLDER%\..
 - python unsung-anthem\utils\build-script --develop-script -v
 - python .\script\build-script --preset=%ANTHEM_PRESET% -v
