version: '0.1.0-dev.{build}'

image:
 - Visual Studio 2015
 - Visual Studio 2017

platform:
 - x86
 - x64

configuration: Debug

environment:
  ANTHEM_OAUTH:
    secure: 9v/VvJm25wmGY1pEfu1jKPfjlY0S3/XD+/V4QcNAs9p0sNUSkmzuAvYK8IobENjd

before_build:
 - IF /i "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2015" SETX ANTHEM_CMAKE_GENERATOR Visual_Studio_14_2015
 - IF /i "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" SETX ANTHEM_CMAKE_GENERATOR Visual_Studio_15_2017
 - pip install requests
 - cd %APPVEYOR_BUILD_FOLDER%\..
 - IF /i "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2015" python unsung-anthem\utils\build-script --preset=appveyor_windows_vs14
 - IF /i "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" python unsung-anthem\utils\build-script --preset=appveyor_windows_vs15

build:
  parallel: true
  project: "%APPVEYOR_BUILD_FOLDER%\\..\\build\\CMake-%ANTHEM_CMAKE_GENERATOR%-DebugAssert+no-llvm\\anthem-windows-x86_64\\anthem.sln"

after_build:
 - cd %APPVEYOR_BUILD_FOLDER%\..\build\CMake-%ANTHEM_CMAKE_GENERATOR%-DebugAssert+no-llvm\anthem-windows-x86_64
 - dir /b/s *
