version: '0.1.0-dev.{build}'

image:
 - Visual Studio 2015
 - Visual Studio 2017

platform:
 - x86
 - x64

configuration: Debug

before_build:
 - pip install requests
 - cd %APPVEYOR_BUILD_FOLDER%\..
 - python unsung-anthem\utils\build-script --preset=appveyor_windows_vs15
