version: 2

defaults: &defaults
  machine:
    - image: circleci/classic:latest
  environment:
    ANTHEM_ROOT: $CIRCLE_WORKING_DIRECTORY/unsung-anthem

jobs:
  build:
    working_directory: ~/anthem/anthem
    machine:
      image: circleci/classic:latest
    environment:
      ANTHEM_BUILD_PRESET: circleci_linux_gcc5_cpp14
      COMPILER_NAME: gcc
      CXX: g++-5
      CC: gcc-5
      ANTHEM_ROOT: ~/anthem/anthem
    steps:
    - checkout
    - run: sudo apt-add-repository -y "ppa:ubuntu-toolchain-r/test"
    - run: sudo apt-get -y update
    - run: sudo apt-get -y --no-install-suggests --no-install-recommends --force-yes install g++-5 xorg-dev libglu1-mesa-dev build-essential
    - run: echo $(pwd)
    - run: ls .
    - run: chmod +x $ANTHEM_ROOT/utils/build-script
    - run: ${CC} --version
    - run: ${CXX} --version
    - run: pip install --user requests
    - run: |
        cd $ANTHEM_ROOT/..
        unsung-anthem/utils/build-script --preset ${ANTHEM_BUILD_PRESET} --install
    - run: |
        cd $ANTHEM_ROOT/..
        unsung-anthem/utils/build-script --preset ${ANTHEM_BUILD_PRESET} --build
    - run: |
        cd $ANTHEM_ROOT/..
        unsung-anthem/utils/build-script --preset ${ANTHEM_BUILD_PRESET} --run-test

workflows:
  version: 2
  build_test:
    jobs:
    - build

