version: 2

defaults: &defaults
  working_directory: /home/circleci/anthem/anthem
  machine:
    image: circleci/classic:latest

default_variables: &default_variables
  ANTHEM_SOURCE_ROOT: /home/circleci/anthem
  ANTHEM_REPO_NAME: anthem

jobs:
  add_apt_sources:
    <<: *defaults
    steps:
    - run: sudo apt-add-repository -y "ppa:ubuntu-toolchain-r/test"
    - run: sudo apt-add-repository -y "llvm-toolchain-trusty"
    - run: sudo apt-add-repository -y "llvm-toolchain-trusty-4.0"

  apt_update:
    <<: *defaults
    steps:
    - run: sudo apt-get -y update

  install_default_packages:
    - run: sudo apt-get -y --no-install-suggests --no-install-recommends --force-yes install xorg-dev libglu1-mesa-dev build-essential

  build_gcc_cpp14:
    <<: *defaults
    environment:
      <<: *default_variables
      ANTHEM_BUILD_PRESET: circleci_linux_gcc5_cpp14
      COMPILER_NAME: gcc
      CXX: g++-5
      CC: gcc-5
    steps:
    - checkout
    - run: sudo apt-get -y --no-install-suggests --no-install-recommends --force-yes install g++-5
    - run: |
        cd $CIRCLE_WORKING_DIRECTORY/..
        chmod +x $ANTHEM_REPO_NAME/utils/build-script
    - run: ${CC} --version
    - run: ${CXX} --version
    - run: pip install --user requests
    - run: |
        cd $CIRCLE_WORKING_DIRECTORY/..
        $ANTHEM_REPO_NAME/utils/build-script --preset ${ANTHEM_BUILD_PRESET} --install
    - run: |
        cd $CIRCLE_WORKING_DIRECTORY/..
        $ANTHEM_REPO_NAME/utils/build-script --preset ${ANTHEM_BUILD_PRESET} --build
    - run: |
        cd $CIRCLE_WORKING_DIRECTORY/..
        $ANTHEM_REPO_NAME/utils/build-script --preset ${ANTHEM_BUILD_PRESET} --run-test

workflows:
  version: 2
  build_test:
    jobs:
    - add_apt_sources
    - apt_update:
        requires:
        - add_apt_sources
    - install_default_packages:
        requires:
        - apt_update
    - build_gcc_cpp14:
        requires:
        - install_default_packages
