#===------------------------------ config.yml ------------------------------===#
#
#                         Obliging Ode & Unsung Anthem
#
# This source file is part of the Obliging Ode and Unsung Anthem open source
# projects.
#
# Copyright (c) 2018 Venturesome Stone
# Licensed under GNU Affero General Public License v3.0

version: 2

defaults: &defaults
  working_directory: /home/circleci/anthem/anthem
  machine:
    image: circleci/classic:latest
  parallelism: 1

default_variables: &default_variables
  ANTHEM_SOURCE_ROOT: /home/circleci/anthem
  ANTHEM_REPO_NAME: anthem

jobs:
  #===----------------------------------------------------------------------===#
  #==- GNU Compiler Collection ----------------------------------------------==#
  #===----------------------------------------------------------------------===#

  #==- C++17 GNU Compiler Collection 7 --------------------------------------==#

  gcc7_cxx17:
    <<: *defaults
    environment:
      <<: *default_variables
      BUILD_PRESET: circleci_linux_gcc7_cxx17
      COMPILER_NAME: gcc
      CXX: g++-7
      CC: gcc-7
    steps:
    - checkout
    - run: sudo apt-add-repository -y "ppa:ubuntu-toolchain-r/test"
    - run: sudo apt-get -y update
    - run: sudo apt-get -y --no-install-suggests --no-install-recommends --force-yes install g++-7 xorg-dev libglu1-mesa-dev build-essential
    - run: |
        cd $CIRCLE_WORKING_DIRECTORY/..
        chmod +x $ANTHEM_REPO_NAME/utils/build-script
    - run: ${CC} --version
    - run: ${CXX} --version
    - run: pip install --user requests
    - run: |
        cd $CIRCLE_WORKING_DIRECTORY/..
        $ANTHEM_REPO_NAME/utils/build-script --develop-script -v
    - run: |
        cd $CIRCLE_WORKING_DIRECTORY/..
        ./script/build-script --preset ${BUILD_PRESET} -v

  #===----------------------------------------------------------------------===#
  #==- Clang ----------------------------------------------------------------==#
  #===----------------------------------------------------------------------===#

  #==- C++17 Clang 6.0 ------------------------------------------------------==#

  clang60_cxx17:
    <<: *defaults
    environment:
      <<: *default_variables
      BUILD_PRESET: circleci_linux_clang60_cxx17
    steps:
    - checkout
    - run: sudo apt-add-repository -y "ppa:ubuntu-toolchain-r/test"
    - run: sudo apt-get -y update
    - run: sudo apt-get -y --no-install-suggests --no-install-recommends --force-yes install xorg-dev libglu1-mesa-dev build-essential
    - run: |
        cd $CIRCLE_WORKING_DIRECTORY/..
        chmod +x $ANTHEM_REPO_NAME/utils/build-script
    - run: pip install --user requests
    - run: |
        cd $CIRCLE_WORKING_DIRECTORY/..
        $ANTHEM_REPO_NAME/utils/build-script --develop-script -v
    - run: |
        cd $CIRCLE_WORKING_DIRECTORY/..
        ./script/build-script --preset ${BUILD_PRESET} -v


workflows:
  version: 2
  build_and_test:
    jobs:
     - gcc7_cxx17
     - clang60_cxx17
