#===------------------------------ config.yml ------------------------------===#
#
#                         Obliging Ode & Unsung Anthem
#
# This source file is part of the Obliging Ode and Unsung Anthem open source
# projects.
#
# Copyright (c) 2018 Venturesome Stone
# Licensed under GNU Affero General Public License v3.0

version: 2

defaults: &defaults
  working_directory: /home/circleci/anthem/anthem
  machine:
    image: circleci/classic:latest
  parallelism: 1

default_variables: &default_variables
  ANTHEM_SOURCE_ROOT: /home/circleci/anthem
  ANTHEM_REPO_NAME: anthem

jobs:
  #===----------------------------------------------------------------------===#
  #==- GNU Compiler Collection ----------------------------------------------==#
  #===----------------------------------------------------------------------===#

  #==- C++14 GNU Compiler Collection 5 --------------------------------------==#

  gcc5_cxx14:
    <<: *defaults
    environment:
      <<: *default_variables
      BUILD_PRESET: circleci_linux_gcc5_cxx14
      COMPILER_NAME: gcc
      CXX: g++-5
      CC: gcc-5
    steps:
    - checkout
    - run: sudo apt-add-repository -y "ppa:ubuntu-toolchain-r/test"
    - run: sudo apt-get -y update
    - run: sudo apt-get -y --no-install-suggests --no-install-recommends --force-yes install g++-5 xorg-dev libglu1-mesa-dev build-essential
    - run: |
        cd $CIRCLE_WORKING_DIRECTORY/..
        chmod +x $ANTHEM_REPO_NAME/utils/build-script
    - run: ${CC} --version
    - run: ${CXX} --version
    - run: pip install --user requests
    - run: |
        cd $CIRCLE_WORKING_DIRECTORY/..
        $ANTHEM_REPO_NAME/utils/build-script --preset ${BUILD_PRESET}


  #==- C++14 GNU Compiler Collection 6 --------------------------------------==#

  gcc6_cxx14:
    <<: *defaults
    environment:
      <<: *default_variables
      BUILD_PRESET: circleci_linux_gcc6_cxx14
      COMPILER_NAME: gcc
      CXX: g++-6
      CC: gcc-6
    steps:
    - checkout
    - run: sudo apt-add-repository -y "ppa:ubuntu-toolchain-r/test"
    - run: sudo apt-get -y update
    - run: sudo apt-get -y --no-install-suggests --no-install-recommends --force-yes install g++-6 xorg-dev libglu1-mesa-dev build-essential
    - run: |
        cd $CIRCLE_WORKING_DIRECTORY/..
        chmod +x $ANTHEM_REPO_NAME/utils/build-script
    - run: ${CC} --version
    - run: ${CXX} --version
    - run: pip install --user requests
    - run: |
        cd $CIRCLE_WORKING_DIRECTORY/..
        $ANTHEM_REPO_NAME/utils/build-script --preset ${BUILD_PRESET}


  #==- C++14 GNU Compiler Collection 7 --------------------------------------==#

  gcc7_cxx14:
    <<: *defaults
    environment:
      <<: *default_variables
      BUILD_PRESET: circleci_linux_gcc7_cxx14
      COMPILER_NAME: gcc
      CXX: g++-7
      CC: gcc-7
    steps:
    - checkout
    - run: sudo apt-add-repository -y "ppa:ubuntu-toolchain-r/test"
    - run: sudo apt-get -y update
    - run: sudo apt-get -y --no-install-suggests --no-install-recommends --force-yes install g++-7 xorg-dev libglu1-mesa-dev build-essential
    - run: |
        cd $CIRCLE_WORKING_DIRECTORY/..
        chmod +x $ANTHEM_REPO_NAME/utils/build-script
    - run: ${CC} --version
    - run: ${CXX} --version
    - run: pip install --user requests
    - run: |
        cd $CIRCLE_WORKING_DIRECTORY/..
        $ANTHEM_REPO_NAME/utils/build-script --preset ${BUILD_PRESET}


  #==- C++17 GNU Compiler Collection 7 --------------------------------------==#

  gcc7_cxx17:
    <<: *defaults
    environment:
      <<: *default_variables
      BUILD_PRESET: circleci_linux_gcc7_cxx17
      COMPILER_NAME: gcc
      CXX: g++-7
      CC: gcc-7
    steps:
    - checkout
    - run: sudo apt-add-repository -y "ppa:ubuntu-toolchain-r/test"
    - run: sudo apt-get -y update
    - run: sudo apt-get -y --no-install-suggests --no-install-recommends --force-yes install g++-7 xorg-dev libglu1-mesa-dev build-essential
    - run: |
        cd $CIRCLE_WORKING_DIRECTORY/..
        chmod +x $ANTHEM_REPO_NAME/utils/build-script
    - run: ${CC} --version
    - run: ${CXX} --version
    - run: pip install --user requests
    - run: |
        cd $CIRCLE_WORKING_DIRECTORY/..
        $ANTHEM_REPO_NAME/utils/build-script --preset ${BUILD_PRESET}

  #===----------------------------------------------------------------------===#
  #==- Clang ----------------------------------------------------------------==#
  #===----------------------------------------------------------------------===#


  #==- C++14 Clang 3.6 ------------------------------------------------------==#

  clang36_cxx14:
    <<: *defaults
    environment:
      <<: *default_variables
      BUILD_PRESET: circleci_linux_clang36_cxx14
      COMPILER_NAME: clang
      CXX: clang++-3.6
      CC: clang-3.6
    steps:
    - checkout
    - run: sudo apt-add-repository -y "ppa:ubuntu-toolchain-r/test"
    - run: sudo apt-add-repository -y "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.6 main"
    - run: sudo apt-get -y update
    - run: sudo apt-get -y --no-install-suggests --no-install-recommends --force-yes install clang-3.6 libc++-dev xorg-dev libglu1-mesa-dev build-essential
    - run: |
        cd $CIRCLE_WORKING_DIRECTORY/..
        chmod +x $ANTHEM_REPO_NAME/utils/build-script
    - run: ${CC} --version
    - run: ${CXX} --version
    - run: pip install --user requests
    - run: |
        cd $CIRCLE_WORKING_DIRECTORY/..
        $ANTHEM_REPO_NAME/utils/build-script --preset ${BUILD_PRESET}


  #==- C++14 Clang 3.7 ------------------------------------------------------==#

  clang37_cxx14:
    <<: *defaults
    environment:
      <<: *default_variables
      BUILD_PRESET: circleci_linux_clang37_cxx14
      COMPILER_NAME: clang
      CXX: clang++-3.7
      CC: clang-3.7
    steps:
    - checkout
    - run: sudo apt-add-repository -y "ppa:ubuntu-toolchain-r/test"
    - run: sudo apt-add-repository -y "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.7 main"
    - run: sudo apt-get -y update
    - run: sudo apt-get -y --no-install-suggests --no-install-recommends --force-yes install clang-3.7 libc++-dev xorg-dev libglu1-mesa-dev build-essential
    - run: |
        cd $CIRCLE_WORKING_DIRECTORY/..
        chmod +x $ANTHEM_REPO_NAME/utils/build-script
    - run: ${CC} --version
    - run: ${CXX} --version
    - run: pip install --user requests
    - run: |
        cd $CIRCLE_WORKING_DIRECTORY/..
        $ANTHEM_REPO_NAME/utils/build-script --preset ${BUILD_PRESET}


  #==- C++14 Clang 3.8 ------------------------------------------------------==#

  clang38_cxx14:
    <<: *defaults
    environment:
      <<: *default_variables
      BUILD_PRESET: circleci_linux_clang38_cxx14
      COMPILER_NAME: clang
      CXX: clang++-3.8
      CC: clang-3.8
    steps:
    - checkout
    - run: sudo apt-add-repository -y "ppa:ubuntu-toolchain-r/test"
    - run: sudo apt-add-repository -y "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.8 main"
    - run: sudo apt-get -y update
    - run: sudo apt-get -y --no-install-suggests --no-install-recommends --force-yes install clang-3.8 libc++-dev xorg-dev libglu1-mesa-dev build-essential
    - run: |
        cd $CIRCLE_WORKING_DIRECTORY/..
        chmod +x $ANTHEM_REPO_NAME/utils/build-script
    - run: ${CC} --version
    - run: ${CXX} --version
    - run: pip install --user requests
    - run: |
        cd usr/lib
        find . -name * -print
    - run: |
        cd $CIRCLE_WORKING_DIRECTORY/..
        $ANTHEM_REPO_NAME/utils/build-script --preset ${BUILD_PRESET}


  #==- C++14 Clang 3.9 ------------------------------------------------------==#

  clang39_cxx14:
    <<: *defaults
    environment:
      <<: *default_variables
      BUILD_PRESET: circleci_linux_clang39_cxx14
      COMPILER_NAME: clang
      CXX: clang++-3.9
      CC: clang-3.9
    steps:
    - checkout
    - run: sudo apt-add-repository -y "ppa:ubuntu-toolchain-r/test"
    - run: sudo apt-add-repository -y "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.9 main"
    - run: sudo apt-get -y update
    - run: sudo apt-get -y --no-install-suggests --no-install-recommends --force-yes install clang-3.9 libc++-dev xorg-dev libglu1-mesa-dev build-essential
    - run: |
        cd $CIRCLE_WORKING_DIRECTORY/..
        chmod +x $ANTHEM_REPO_NAME/utils/build-script
    - run: ${CC} --version
    - run: ${CXX} --version
    - run: pip install --user requests
    - run: |
        cd $CIRCLE_WORKING_DIRECTORY/..
        $ANTHEM_REPO_NAME/utils/build-script --preset ${BUILD_PRESET}


  #==- C++14 Clang 4.0 ------------------------------------------------------==#

  clang40_cxx14:
    <<: *defaults
    environment:
      <<: *default_variables
      BUILD_PRESET: circleci_linux_clang40_cxx14
      COMPILER_NAME: clang
      CXX: clang++-4.0
      CC: clang-4.0
    steps:
    - checkout
    - run: sudo apt-add-repository -y "ppa:ubuntu-toolchain-r/test"
    - run: sudo apt-add-repository -y "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-4.0 main"
    - run: sudo apt-get -y update
    - run: sudo apt-get -y --no-install-suggests --no-install-recommends --force-yes install clang-4.0 libc++-dev xorg-dev libglu1-mesa-dev build-essential
    - run: |
        cd $CIRCLE_WORKING_DIRECTORY/..
        chmod +x $ANTHEM_REPO_NAME/utils/build-script
    - run: ${CC} --version
    - run: ${CXX} --version
    - run: pip install --user requests
    - run: |
        cd $CIRCLE_WORKING_DIRECTORY/..
        $ANTHEM_REPO_NAME/utils/build-script --preset ${BUILD_PRESET}


  #==- C++14 Clang 5.0 ------------------------------------------------------==#

  clang50_cxx14:
    <<: *defaults
    environment:
      <<: *default_variables
      BUILD_PRESET: circleci_linux_clang50_cxx14
      COMPILER_NAME: clang
      CXX: clang++-5.0
      CC: clang-5.0
    steps:
    - checkout
    - run: sudo apt-add-repository -y "ppa:ubuntu-toolchain-r/test"
    - run: sudo apt-add-repository -y "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-5.0 main"
    - run: sudo apt-get -y update
    - run: sudo apt-get -y --no-install-suggests --no-install-recommends --force-yes install clang-5.0 libc++-dev xorg-dev libglu1-mesa-dev build-essential
    - run: |
        cd $CIRCLE_WORKING_DIRECTORY/..
        chmod +x $ANTHEM_REPO_NAME/utils/build-script
    - run: ${CC} --version
    - run: ${CXX} --version
    - run: pip install --user requests
    - run: |
        cd $CIRCLE_WORKING_DIRECTORY/..
        $ANTHEM_REPO_NAME/utils/build-script --preset ${BUILD_PRESET}


  #==- C++17 Clang 5.0 ------------------------------------------------------==#

  clang50_cxx17:
    <<: *defaults
    environment:
      <<: *default_variables
      BUILD_PRESET: circleci_linux_clang50_cxx17
      COMPILER_NAME: clang
      CXX: clang++-5.0
      CC: clang-5.0
    steps:
    - checkout
    - run: sudo apt-add-repository -y "ppa:ubuntu-toolchain-r/test"
    - run: sudo apt-add-repository -y "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-5.0 main"
    - run: sudo apt-get -y update
    - run: sudo apt-get -y --no-install-suggests --no-install-recommends --force-yes install clang-5.0 libc++-dev xorg-dev libglu1-mesa-dev build-essential
    - run: |
        cd $CIRCLE_WORKING_DIRECTORY/..
        chmod +x $ANTHEM_REPO_NAME/utils/build-script
    - run: ${CC} --version
    - run: ${CXX} --version
    - run: pip install --user requests
    - run: |
        cd $CIRCLE_WORKING_DIRECTORY/..
        $ANTHEM_REPO_NAME/utils/build-script --preset ${BUILD_PRESET}


workflows:
  version: 2
  build_and_test:
    jobs:
     - gcc5_cxx14
     - gcc6_cxx14
     - gcc7_cxx14
     - gcc7_cxx17
     - clang36_cxx14
     - clang37_cxx14
     - clang38_cxx14
     - clang39_cxx14
     - clang40_cxx14
     - clang50_cxx14
     # - clang50_cxx17
