#!/usr/bin/env python

# ------------------------------------------------------------- #
#                 Obliging Ode & Unsung Anthem
# ------------------------------------------------------------- #
#
# This source file is part of the Obliging Ode and Unsung Anthem
# projects.
#
# Copyright (C) 2019 Antti Kivi
# All rights reserved
#
# ------------------------------------------------------------- #

"""This tool builds Obliging Ode and Unsung Anthem."""


import sys

from composer import runner


def _main():
    return runner.build()


if __name__ == "__main__":
    sys.exit(_main())
