#!/bin/sh

# ---------------------------------------------------------------------------- #
#                         Obliging Ode & Unsung Anthem
# ---------------------------------------------------------------------------- #
#
# This source file is part of the Obliging Ode and Unsung Anthem projects.
#
# Copyright (c) 2019 Antti Kivi
# All rights reserved
#
# ---------------------------------------------------------------------------- #

readonly ODE_NAME="Obliging Ode"
readonly ANTHEM_NAME="Unsung Anthem"

readonly PRINT_DEBUG_OPTION="--print-debug"

readonly COMPOSER_VERSION="0.4.5"
readonly COMPOSER_NAME="Couplet Composer"

readonly GITHUB_URL="https://github.com"
readonly COMPOSER_REPO_OWNER="anttikivi"
readonly COMPOSER_REPO_NAME="couplet-composer"
readonly COMPOSER_REPO_URL="$GITHUB_URL/$COMPOSER_REPO_OWNER/\
$COMPOSER_REPO_NAME.git"

readonly ROOT_DIR="."
readonly COMPOSER_DIRECTORY_NAME="composer"
readonly COMPOSER_DIRECTORY="$ROOT_DIR/$COMPOSER_DIRECTORY_NAME"
readonly BUILD_DIRECTORY_NAME="build"
readonly BUILD_DIRECTORY="$ROOT_DIR/$BUILD_DIRECTORY_NAME"

readonly CLEAN_BUILD_OPTION="-c"
readonly CLEAN_BUILD_SHORT_OPTION="--clean"

readonly PRESET_MODE_ARGUMENT="preset"
readonly CONFIGURE_MODE_ARGUMENT="configure"
readonly COMPOSE_MODE_ARGUMENT="compose"

readonly COMPOSER_EXECUTABLE_NAME="couplet-composer"
