#!/bin/bash

# ------------------------------------------------------------- #
#                 Obliging Ode & Unsung Anthem
# ------------------------------------------------------------- #
#
# This source file is part of the Obliging Ode and Unsung Anthem
# projects.
#
# Copyright (C) 2019 Antti Kivi
# All rights reserved
#
# ------------------------------------------------------------- #

# ------------------------------------------------------------- #
# Constants
# ------------------------------------------------------------- #

readonly ROOT_DIR="."
readonly COMPOSER_REPO_NAME="couplet-composer"
readonly COMPOSER_REPO="$ROOT_DIR/$COMPOSER_REPO_NAME"
readonly BUILD_DIR="$ROOT_DIR/build"
readonly COMPOSER_SCRIPT_DIR="$BUILD_DIR/script"
readonly COMPOSER_SCRIPT_RUN="$COMPOSER_SCRIPT_DIR/run.py"
readonly GRAPHQL_DIR="$BUILD_DIR/graphql"
readonly DEV_STACK_LONG_ARG="--development-stack"
readonly DEV_STACK_SHORT_ARG="-S"

# ------------------------------------------------------------- #
# Variables
# ------------------------------------------------------------- #

dev_stack=false

# ------------------------------------------------------------- #
# Checks if the development stack is already in use and take it
# into use if it isn't already
# ------------------------------------------------------------- #

set_dev_stack() {
  if [[ $dev_stack == true ]]; then
    echo "The development stack is already taken in use" 1>&2
    exit 4
  else
    dev_stack=true
  fi
}

# ------------------------------------------------------------- #
# Loop through the command line arguments
# ------------------------------------------------------------- #

for arg in "$@"; do
  if [[ "$arg" == $DEV_STACK_LONG_ARG ]]; then
    set_dev_stack
  fi
  if [[ "$arg" == $DEV_STACK_SHORT_ARG ]]; then
    set_dev_stack
  fi
done

# TODO The development stack is currently always on
dev_stack=true

echo "The development stack is automatically turned on"

# ------------------------------------------------------------- #
# Create the build directory if it doesn't exist
# ------------------------------------------------------------- #

if [[ ! -d $BUILD_DIR ]]; then
  mkdir -p $BUILD_DIR
fi

# ------------------------------------------------------------- #
# Copies a directory to the composer directory from the
# development stack composer
# ------------------------------------------------------------- #

copy_dev_dir() {
  cp -r $COMPOSER_REPO/$1 $COMPOSER_SCRIPT_DIR/$1
}

# ------------------------------------------------------------- #
# Copies a file to the composer directory from the development
# stack composer
# ------------------------------------------------------------- #

copy_dev_file() {
  cp $COMPOSER_REPO/$1 $COMPOSER_SCRIPT_DIR/$1
}

# ------------------------------------------------------------- #
# If the development stack is used, copy the files to the right
# location
# ------------------------------------------------------------- #

if [[ $dev_stack == true ]]; then
  if [[ -d $COMPOSER_SCRIPT_DIR ]]; then
    rm -rf $COMPOSER_SCRIPT_DIR
  fi

  mkdir $COMPOSER_SCRIPT_DIR

  # copy_dev_dir components
  # copy_dev_dir github
  copy_dev_dir couplet_composer
  copy_dev_dir support
  copy_dev_dir util

  copy_dev_file run.py

  if [[ -d $GRAPHQL_DIR ]]; then
    rm -rf $GRAPHQL_DIR
  fi

  mkdir $GRAPHQL_DIR
fi

# ------------------------------------------------------------- #
# Call the Python script
# ------------------------------------------------------------- #

python $COMPOSER_SCRIPT_RUN bootstrap "$@"
