#!/usr/bin/env python

# ------------------------------------------------------------- #
#                 Obliging Ode & Unsung Anthem
# ------------------------------------------------------------- #
#
# This source file is part of the Obliging Ode and Unsung Anthem
# projects.
#
# Copyright (C) 2019 Antti Kivi
# All rights reserved
#
# ------------------------------------------------------------- #


"""
This tool sets up the dependencies of Obliging Ode and Unsung
Anthem so you can develop and build them.
"""


from __future__ import print_function

import os
import platform
import shutil
import subprocess
import sys


USE_DEVELOP_STACK = any([(opt == "--develop-stack") for opt in sys.argv[1:]])
DRY_RUN = any([(opt == "-n" or opt == "--dry-run") for opt in sys.argv[1:]])


ODE_DEFAULT_BUILD_VERSION = "0.3.0"
ODE_BUILD_KEY = "ode-composer"
REPO_OWNER = "anttikivi"
REPO_NAME = ODE_BUILD_KEY
BUILD_LOCATION = os.path.join("build")
BUILD_SCRIPT_LOCATION = os.path.join(BUILD_LOCATION, "script")


ODE_BUILD_VERSION = "develop" \
    if USE_DEVELOP_STACK \
    else ODE_DEFAULT_BUILD_VERSION


def _copy_script_dev():
    if not os.path.isdir(BUILD_LOCATION):
        print("The directory " + BUILD_LOCATION + " doesn't exist")
        os.makedirs(BUILD_LOCATION)
    else:
        if os.path.isdir(BUILD_SCRIPT_LOCATION):
            shutil.rmtree(BUILD_SCRIPT_LOCATION)
            os.makedirs(BUILD_SCRIPT_LOCATION)
    src_dir = os.path.join(REPO_NAME, "src")
    for item in os.listdir(src_dir):
        src = os.path.join(src_dir, item)
        dest = os.path.join(BUILD_SCRIPT_LOCATION, item)
        if os.path.isdir(src):
            shutil.copytree(src, dest)
        else:
            shutil.copy2(src, dest)


def caffeinate(command):
    """
    Run a command during which system sleep is disabled. This
    ignores the 'shell.dry_run' flag.
    """
    # Disable system sleep, if possible.
    if platform.system() == "Darwin":
        # Don't change the caller's copy of the arguments.
        command = ["caffeinate"] + list(command)
    try:
        subprocess.check_call(command)
    except subprocess.CalledProcessError as e:
        SystemExit(
            "Command ended with a non-zero exit status "
            "{}".format(e.returncode))
    except OSError as e:
        SystemExit("Could not run the build script: {}".format(e.strerror))


def _run_dev():
    _copy_script_dev()
    args = [sys.executable]
    args += [os.path.join(BUILD_SCRIPT_LOCATION, "bootstrap")]
    args += sys.argv[1:]
    return caffeinate(args)


def _main():
    if USE_DEVELOP_STACK:
        print(
            "Ode Composer and related project won't be downloaded as you "
            "chose the development stack")
        return _run_dev()
    else:
        # _checkout(_download_v4)
        return 0  # _run()


if __name__ == "__main__":
    sys.exit(_main())
