#!/bin/bash

# ------------------------------------------------------------- #
#                 Obliging Ode & Unsung Anthem
# ------------------------------------------------------------- #
#
# This source file is part of the Obliging Ode and Unsung Anthem
# projects.
#
# Copyright (c) 2019 Antti Kivi
# All rights reserved
#
# ------------------------------------------------------------- #

# ------------------------------------------------------------- #
# Constants
# ------------------------------------------------------------- #

readonly PRESET_MODE_ARGUMENT="preset"
readonly COMPOSE_MODE_ARGUMENT="compose"

readonly COMPOSER_EXECUTABLE_NAME="composer"

# ------------------------------------------------------------- #
# Run the build script
# ------------------------------------------------------------- #

preset_mode=false

for arg in "$@"; do
  if [[ "$arg" == $PRESET_MODE_OPTION ]]; then
    preset_mode=true
  fi
done

if [[ $preset_mode == true ]]; then
  $COMPOSER_EXECUTABLE_NAME $PRESET_MODE_ARGUMENT "$@" $COMPOSE_MODE_ARGUMENT
else
  $COMPOSER_EXECUTABLE_NAME $COMPOSE_MODE_ARGUMENT "$@"
fi
