@rem Copyright (c) 2020 Antti Kivi
@rem Licensed under the Effective Elegy Licence

@echo off

set composer_name=Couplet Composer
set ode_name=Obliging Ode
set anthem_name=Unsung Anthem

echo Running the Windows batch file wrapper for %composer_name%, the build ^
script of %ode_name% and %anthem_name%
echo %composer_name% will be run in composing mode

set root_dir=%cd%

set build_directory_name=build
set project_directory_name=unsung-anthem

set build_directory=%root_dir%\%build_directory_name%
set in_tree_build_directory=%root_dir%\%project_directory_name%\^
%build_directory_name%

set in_tree_build_option=--in-tree-build

set preset_mode_argument=preset
set compose_mode_argument=compose

set composer_executable_name=couplet-composer

@rem See if the directory generated by configuring mode is in place

set in_tree_build=false

if "%~1"=="%in_tree_build_option%" set in_tree_build=true

if not exist %build_directory% (
  if %in_tree_build_option%==false (
    echo The directory %build_directory% is missing
    goto exit_for_missing_configuration
  )
)

if not exist %in_tree_build_directory% (
  if %in_tree_build_option%==true (
    echo The directory %in_tree_build_directory% is missing
    goto exit_for_missing_configuration
  )
)

@rem Set up Couplet Composer

set current_directory=%~dp0

call %current_directory%\set_up.bat %*

@rem Run Couplet Composer

set preset_mode=false

if "%~1"=="%preset_mode_argument%" set preset_mode=true

if %preset_mode%==true (
  start "%composer_name%" /w /b pipenv run %composer_executable_name% %* ^
%compose_mode_argument%
) else (
  start "%composer_name%" /w /b pipenv run %composer_executable_name% ^
%compose_mode_argument% %*
)

goto :eof

:exit_for_missing_configuration
echo The build directory wasn't found; please make sure to run the cofiguring ^
script before attempting to build %ode_name% and %anthem_name% 1>&2
exit 1
