#!/bin/sh

# Copyright (c) 2020 Antti Kivi
# Licensed under the Effective Elegy Licence

current_directory="${0%/*}"

cd $current_directory/..

echo "Changed to directory $current_directory/.."

format_directory() {
  echo "Looking through $1"
  for pathname in "$1"/*; do
    if [ -d "$pathname" ]; then
      format_directory "$pathname"
    elif [ -e "$pathname" ]; then
      case "$pathname" in
        *.txt)
        echo "Skipping: $pathname"
        ;;
        ./include/*|./lib/*|./src/*|./test/*)
        echo "Formatting: $pathname"
        clang-format -i "$pathname"
        ;;
        *)
        echo "Skipping $pathname"
        ;;
      esac
    fi
  done
}

format_directory .
