#!/bin/sh

# Copyright (c) 2020 Antti Kivi
# Licensed under the Effective Elegy Licence

set -e

readonly COMPOSER_VERSION="$(cat ${0%/*}/composer-version)"
readonly COMPOSER_VERSION_TAG="v$COMPOSER_VERSION"
readonly COMPOSER_NAME="Couplet Composer"
readonly ODE_NAME="Obliging Ode"
readonly ANTHEM_NAME="Unsung Anthem"

echo "Running the set-up shell script for $COMPOSER_NAME $COMPOSER_VERSION, \
the build script of $ODE_NAME and $ANTHEM_NAME"

readonly GITHUB_URL="https://github.com"
readonly COMPOSER_REPO_OWNER="anttikivi"
readonly COMPOSER_REPO_NAME="couplet-composer"
readonly COMPOSER_REPO_URL="$GITHUB_URL/$COMPOSER_REPO_OWNER/\
$COMPOSER_REPO_NAME.git"

readonly IN_TREE_BUILD_OPTION="--in-tree-build"

# See if the build should be done in tree.

in_tree_build=false

for arg in "$@"; do
  if [ "$arg" = "$IN_TREE_BUILD_OPTION" ]; then
    in_tree_build=true
  fi
done

echo "The value for in-tree build is set to $in_tree_build"

# Switch to the correct directory.

if [ "$in_tree_build" = false ]; then
  cd ..
fi

echo "The working directory is set to $PWD"

readonly SCRIPT_DIRECTORY_NAME="script"
readonly COMPOSER_DIRECTORY_BASE_NAME="composer"
# TODO Also replace hyphens by underscores.
readonly COMPOSER_DIRECTORY_NAME="${COMPOSER_DIRECTORY_BASE_NAME}_\
$(echo $COMPOSER_VERSION | tr '.' '_')"
readonly COMPOSER_HEAD_DIRECTORY_NAME="${COMPOSER_DIRECTORY_BASE_NAME}_head"

if [ "$in_tree_build" = true ]; then
  readonly BUILD_DIRECTORY_NAME="build"
  readonly BUILD_DIRECTORY="$PWD/$BUILD_DIRECTORY_NAME"
  readonly SCRIPT_DIRECTORY="$BUILD_DIRECTORY/$SCRIPT_DIRECTORY_NAME"

  if [ ! -d "$BUILD_DIRECTORY" ]; then
    mkdir $BUILD_DIRECTORY
    echo "Created the directory '$BUILD_DIRECTORY'"
  fi
else
  readonly SCRIPT_DIRECTORY="$PWD/$SCRIPT_DIRECTORY_NAME"
fi

# Install pipenv.

command -v pipenv >/dev/null 2>&1 || {
  echo >&2 "Didn't find pipenv. Installing."
  pip install pipenv
}

# Set up the script directory.

if [ ! -d "$SCRIPT_DIRECTORY" ]; then
  mkdir $SCRIPT_DIRECTORY
  echo "Created the directory '$SCRIPT_DIRECTORY'"
fi

# Clone Couplet Composer.

if [ "$ODE_DEVELOPMENT_COMPOSER" = true ]; then
  echo "Using development version of $COMPOSER_NAME"

  composer_directory="$SCRIPT_DIRECTORY/$COMPOSER_HEAD_DIRECTORY_NAME"

  # If the Composer directory doesn't exist, there is no need to check for the
  # remote HEAD SHA1.
  if [ ! -d "$composer_directory" ]; then
    echo "The directory '$composer_directory' doesn't exist and, thus, \
$COMPOSER_NAME will be cloned"

    git clone $COMPOSER_REPO_URL $composer_directory
    head_sha="$(git -C "$composer_directory" rev-parse HEAD)"

    echo "The SHA1 for the currently cloned HEAD of $COMPOSER_NAME is $head_sha"
  else
    git -C $composer_directory fetch
    head_sha="$(git -C $composer_directory rev-parse HEAD)"
    origin_sha="$(git -C $composer_directory rev-parse origin/develop)"

    echo "The SHA1 for the currently cloned HEAD of $COMPOSER_NAME is $head_sha"
    echo "The SHA1 for origin/develop of $COMPOSER_NAME is $origin_sha"

    if [ "$head_sha" != "$origin_sha" ]; then
      echo "The SHA1's for origin/develop and local HEAD of $COMPOSER_NAME \
don't match and thus the local copy will be reset"
      git -C $composer_directory reset --hard HEAD
      git -C $composer_directory clean -xffd
      git -C $composer_directory pull
    fi
  fi
  echo "The latest development version of $COMPOSER_NAME is now set up"
else
  composer_directory="$SCRIPT_DIRECTORY/$COMPOSER_DIRECTORY_NAME"

  if [ ! -d "$composer_directory" ]; then
    git clone $COMPOSER_REPO_URL $composer_directory
    git -C $composer_directory checkout tags/$COMPOSER_VERSION_TAG \
-b local_install_$COMPOSER_VERSION_TAG
  fi
fi

pipenv install $composer_directory
