# unsung-anthem/lib/util/BUILD -----------------------------------*- python -*-
#
# This source file is part of the Unsung Anthem open source project.
#
# Copyright (c) 2017 Venturesome Stone
# Licensed under GNU Affero General Public License v3.0


cc_library(name = "monad",
           srcs = ["main.cpp"],
           deps = ["//src:execute"],
           visibility = ["//visibility:public"])


cc_library(name = "execute",
           srcs = ["execute.cpp"],
           hdrs = ["execute.h"])
