name: Lines of code

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        sudo npm install -g cloc
        which xvfb
    - name: Count the lines of code
      run: cloc .
