name: Format code

on: [push]

jobs:
  format:

    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Check out the project
      uses: actions/checkout@v2.0.0
    - name: Run the formatting script
      run: |
        cd $GITHUB_WORKSPACE/..
        echo $PWD
        ./unsung-anthem/util/format
      if: runner.os != 'Windows'
    - name: Run the formatting script on Windows
      run: |
        cd %GITHUB_WORKSPACE%\..
        echo %cd%
        .\unsung-anthem\util\format
      if: runner.os == 'Windows'
      shell: cmd
