name: Linter workflow

on:
  schedule:
  - cron: '0 12 * * 0'
  pull_request:
    types: [opened, edited]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      LOCAL_VERSION_NUMBER_FILE: build_version.txt
    steps:
    - name: Check out the project
      uses: actions/checkout@v2.3.3
    - name: Set up Python
      uses: actions/setup-python@v2.1.3
      with:
        python-version: 3.x
        architecture: x64
    - name: Determine project version
      id: version
      uses: anttikivi/maintain-revision@v0.6.0
      with:
        type: json
        file: util/values.json
    - name: Install APT dependencies
      run: |
        sudo apt-get update
        sudo apt-get install lcov libreadline-dev xorg-dev xvfb xserver-xorg-core xserver-xorg xserver-xorg-video-all xserver-xorg-input-all libasound2-dev libpulse-dev libaudio-dev libx11-dev libxext-dev libxrandr-dev libxcursor-dev libxi-dev libxinerama-dev libxxf86vm-dev libxss-dev libgl1-mesa-dev libdbus-1-dev libudev-dev libgles2-mesa-dev libegl1-mesa-dev libibus-1.0-dev fcitx-libs-dev libsamplerate0-dev libsndio-dev
    - name: Run the configuration
      run: ./configure preset --name main_workflow_${{ runner.os }}_lint --in-tree-build --github-user-agent anttikivi --github-api-token ${{ secrets.GITHUB_TOKEN }} --print-debug
    - name: Run the composition
      run: ./compose preset --name main_workflow_${{ runner.os }}_lint --in-tree-build --github-user-agent anttikivi --github-api-token ${{ secrets.GITHUB_TOKEN }} --print-debug
