name: Main workflow

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Setup Python environment
      uses: actions/setup-python@v1.1.1
      with:
        # Version range or exact version of a Python version to use, using semvers version range syntax.
        python-version: 3.x # optional, default is 3.x
        # The target architecture (x86, x64) of the Python interpreter.
        architecture: x64 # optional, default is x64
    - name: Install Python dependencies
      run: python -m pip install --upgrade pip
    - name: Set up build environment
      run: |
        cd $GITHUB_WORKSPACE/..
        echo "Switched to $GITHUB_WORKSPACE/.."
        ./unsung-anthem/util/configure preset --name main_workflow --print-debug --github-user-agent anttikivi --github-api-token ${{ secrets.GITHUB_TOKEN }}
    - name: Build Obliging Ode and Unsung Anthem
      run: |
        cd $GITHUB_WORKSPACE/..
        echo "Switched to $GITHUB_WORKSPACE/.."
        ./unsung-anthem/util/compose preset --name main_workflow --print-debug --github-user-agent anttikivi --github-api-token ${{ secrets.GITHUB_TOKEN }}
    - name: Run the tests
      run: |
        cd $GITHUB_WORKSPACE/..
        echo "Switched to $GITHUB_WORKSPACE/.."
        echo "TODO"
