name: Quality workflow

on:
  schedule:
  - cron: '0 12 * * 0'
  pull_request:
    types: [opened, edited]

jobs:
  download_version:
    name: Download the development version
    runs-on: ubuntu-18.04
    outputs:
      development_version: ${{ steps.version_increment.outputs.dev_version }}
    steps:
    - name: Install the AWS command line interface
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install
        aws --version
    - name: Download the development version from the bucket
      run: aws s3 cp s3://anthem-workflows/main_workflow/unsung_anthem/dev_version.txt dev_version.txt
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    - id: version_increment
      name: Create the development version
      run: |
        dev_version=`cat dev_version.txt`
        echo "The development version number downloaded from the S3 bucket is $dev_version"
        expr $dev_version + 1 > dev_version_current.txt
        dev_version_current=`cat dev_version_current.txt`
        echo "The development version number for the current run is $dev_version_current"
        echo "::set-output name=dev_version::$dev_version_current"

  lint:
    name: Run linter
    needs: [download_version]
    runs-on: ubuntu-18.04
    env:
      ODE_DEVELOPMENT_VERSION_NUMBER: ${{ needs.download_version.outputs.development_version }}
    steps:
    - name: Check out the project
      uses: actions/checkout@v2.3.1
    - name: Install APT dependencies
      run: |
        sudo apt-get update
        sudo apt-get install lcov libreadline-dev xorg-dev xvfb xserver-xorg-core xserver-xorg xserver-xorg-video-all xserver-xorg-input-all libasound2-dev libpulse-dev libaudio-dev libx11-dev libxext-dev libxrandr-dev libxcursor-dev libxi-dev libxinerama-dev libxxf86vm-dev libxss-dev libgl1-mesa-dev libdbus-1-dev libudev-dev libgles2-mesa-dev libegl1-mesa-dev libibus-1.0-dev fcitx-libs-dev libsamplerate0-dev libsndio-dev
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
        architecture: x64
    - name: Cache the dependencies
      uses: actions/cache@v2.1.1
      with:
        path: build/local
        key: ubuntu-18.04-ode-${{ hashFiles('util/dependencies.json') }}-ninja-${{ github.run_id }}
    - name: Run the configuration
      run: ./configure preset --name main_workflow_${{ runner.os }}_lint --in-tree-build --github-user-agent anttikivi --github-api-token ${{ secrets.GITHUB_TOKEN }} --print-debug
    - name: Run the composition
      run: ./compose preset --name main_workflow_${{ runner.os }}_lint --in-tree-build --github-user-agent anttikivi --github-api-token ${{ secrets.GITHUB_TOKEN }} --print-debug

  coverage:
    name: Upload code coverage
    needs: [download_version]
    runs-on: ubuntu-18.04
    env:
      ODE_DEVELOPMENT_VERSION_NUMBER: ${{ needs.download_version.outputs.development_version }}
    steps:
    - name: Check out the project
      uses: actions/checkout@v2.3.1
    - name: Install APT dependencies
      run: |
        sudo apt-get update
        sudo apt-get install lcov libreadline-dev xorg-dev xvfb xserver-xorg-core xserver-xorg xserver-xorg-video-all xserver-xorg-input-all libasound2-dev libpulse-dev libaudio-dev libx11-dev libxext-dev libxrandr-dev libxcursor-dev libxi-dev libxinerama-dev libxxf86vm-dev libxss-dev libgl1-mesa-dev libdbus-1-dev libudev-dev libgles2-mesa-dev libegl1-mesa-dev libibus-1.0-dev fcitx-libs-dev libsamplerate0-dev libsndio-dev
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
        architecture: x64
    - name: Cache the dependencies
      uses: actions/cache@v2.1.1
      with:
        path: build/local
        key: ubuntu-18.04-ode-${{ hashFiles('util/dependencies.json') }}-make-${{ github.run_id }}
    - name: Run the configuration
      run: ./configure preset --name main_workflow_${{ runner.os }}_coverage --in-tree-build --github-user-agent anttikivi --github-api-token ${{ secrets.GITHUB_TOKEN }} --print-debug
    - name: Run the composition
      run: ./compose preset --name main_workflow_${{ runner.os }}_coverage --in-tree-build --github-user-agent anttikivi --github-api-token ${{ secrets.GITHUB_TOKEN }} --print-debug
    - name: Upload code coverage report
      run: |
        cd $GITHUB_WORKSPACE/build/build/linux-x86_64-debug-unix_makefiles
        bash <(curl -s https://codecov.io/bash) -f anthem_coverage.info
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
