name: Release workflow

on:
  release:
    types: [published]

jobs:
  reset_version:
    name: Reset the development version
    runs-on: ubuntu-18.04
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    steps:
    - name: Install the AWS command line interface
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install
        aws --version
    - name: Set the development version to the file
      run: |
        echo "0" > dev_version.txt
    - name: Delete the old development version from the bucket
      run: aws s3 rm s3://anthem-workflows/main_workflow/unsung_anthem/dev_version.txt
    - name: Upload the development version to the bucket
      run: aws s3 cp dev_version.txt s3://anthem-workflows/main_workflow/unsung_anthem/dev_version.txt
